version: "3.8"
services:
  docker-apache:
    image: my-php-site:latest
    container_name: docker-apache
    ports:
      - "80:80"

db:
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: badcrud
    ports:
      - "3306:3306"
    volumes:
      - ./db/badcrud.sql:/docker-entrypoint-initdb.d/badcrud.sql:ro